### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by yermulnik** [lucasmelin/gh-hook#2]
Hello,

How is shell completion supposed to work? I created completion file with `gh hook completion bash > ~/.bash_completion.d/gh.hook.completion` and sourced it, though apparently it doesn't work to complete `gh hook` sub-commands and parameters. It doesn't work to complete `~/.local/share/gh/extensions/gh-hook/gh-hook` either.

**Comment by lucasmelin** [comment]
👋🏻 Hi there, thanks for pointing this out. Looks like command completion for `gh` extensions is currently unsupported, so I've removed the auto-generated `completion` command until the upstream issue https://github.com/cli/cli/issues/5309 is closed.

**Comment by yermulnik** [comment]
Got you. Thanks for the update.
